fixtures:
  repositories:
    'stdlib':  'git://github.com/puppetlabs/puppetlabs-stdlib'
    'apt':
      repo: 'git://github.com/puppetlabs/puppetlabs-apt.git'
      ref:  '1.4.0'
    'inifile': 'git://github.com/puppetlabs/puppetlabs-inifile'

  symlinks:
    'ceph': "#{source_dir}"
